version: '3'

services:

  ruby:
    container_name: ruby
    image: victorcalisto/solar:1.0.0
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - gems:/usr/local/bundle
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      RAILS_ENV: ${RAILS_ENV}
      PGHOST: ${PGHOST}
      PGPORT: ${PGPORT}
    depends_on:
      - postgres  

  postgres:
    container_name: postgres
    image: postgres:16-bookworm
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  gems:
  data:
